image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

# Build the Docker image
build_backend:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$CI_REGISTRY_IMAGE/backend:latest" ./backend
    - docker push "$CI_REGISTRY_IMAGE/backend:latest"
  only:
    - main

# Deploy the backend to a Docker container
deploy_backend:
  stage: deploy
  script:
    - docker pull "$CI_REGISTRY_IMAGE/backend:latest"
    - docker run -d -p 5000:5000 "$CI_REGISTRY_IMAGE/backend:latest"
  only:
    - main